[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->âœ¨ Features" },
    { message = "^fix", group = "<!-- 1 -->ğŸ› Bug Fixes" },
    { message = "^docs", group = "<!-- 2 -->ğŸ“š Documentation" },
    { message = "^perf", group = "<!-- 3 -->âš¡ Performance" },
    { message = "^refactor", group = "<!-- 4 -->ğŸšœ Refactor" },
    { message = "^style", group = "<!-- 5 -->ğŸ¨ Style" },
    { message = "^test", group = "<!-- 6 -->ğŸ§ª Tests" },
    { message = "^build", group = "<!-- 7 -->ğŸ“¦ Build" },
    { message = "^ci", group = "<!-- 8 -->ğŸš§ CI" },
]
filter_commits = true
